### ISSUE TITLE
Needs tests and error handling

### ISSUE THREAD

**Issue by karthik** [karthik/holepunch#2]

**Comment by benmarwick** [comment]
I've written a test over for `write_compendium_description` in my fork here: https://github.com/benmarwick/holepunch/blob/master/tests/testthat/test-write_compendium_description.R

The catch is that I've replaced your original `get_dependencies` with a modified version of our similar function in [rrtools](https://github.com/benmarwick/rrtools/blob/master/R/manage_dependencies.R). 

I've just copy-pasted it in to my fork `holepunch`. I like it best because it gives the pkg name _and_ version number, which `hadley/requirements` doesn't do. 

What do you think? The approach to testing might be useful, even if you take a different direction with how you scan the dependencies.

**Comment by karthik** [comment]
> I've just copy-pasted it in to my fork holepunch. I like it best because it gives the pkg name and version number, which hadley/requirements doesn't do.

I like this approach. Can you point me to a example where you capture that output? What do you do with the version numbers because you can't request a specific one from CRAN. Is that just useful metadata for purposes other than install?

**Comment by karthik** [comment]
I've done as many tests as I can for now. Still not sure how to test a promise but will leave that for a new issue.
