### ISSUE TITLE
Fix versions by default

### ISSUE THREAD

**Issue by noamross** [karthik/holepunch#35]
I suggest that by default hole punch fix versions for R and packages and print an informative message for packages used. This would involve:
- Picking the appropriate Rocker base based on local R version. 
- Using a runtime.txt to fix the MRAN date
- Identify non-CRAN packages and set appropriate fixed-version Remotes.

**Comment by karthik** [comment]
Right now it scans all the code and picks the version of R matching the last modified date of any file. That way, when someone enables binder on an old repo, we are not inadvertently forcing a newer version of R. So now it will automatically pick a rocker ver date based on file modification date. 

> Using a runtime.txt to fix the MRAN date

Once a Dockerifle is in place, runtime.txt is ignored. The MRAN date is fixed in the Dockerfile. [Example](https://github.com/karthik/btest2/blob/master/.binder/Dockerfile#L7)

> Identify non-CRAN packages and set appropriate fixed-version Remotes.

This is an [open issue](https://github.com/karthik/holepunch/issues/32)
